import type { ExamQuestion } from '@fm/core';
import { withReview } from '../../tools/content-tools/checks/with-review.mts';

/**
 * 题库批量扩产批次（100 题）：六科目主题矩阵生成，
 * 概念/辨析/多选/判断四题型轮换 × 难度梯度，与既有 tag 体系联动。
 */

const s = (id: string, subject: string, chapter: string, tags: string[], stem: string, options: string[], answer: number, explanation: string, difficulty: 1 | 2 | 3 | 4 | 5 = 2): ExamQuestion => {
  return withReview({ id, subject, chapter, knowledge_tags: tags, type: 'single', stem, options, answer, explanation, difficulty });
}
const m = (id: string, subject: string, chapter: string, tags: string[], stem: string, options: string[], answer: number[], explanation: string, difficulty: 1 | 2 | 3 | 4 | 5 = 3): ExamQuestion => {
  return withReview({ id, subject, chapter, knowledge_tags: tags, type: 'multiple', stem, options, answer, explanation, difficulty });
}
const j = (id: string, subject: string, chapter: string, tags: string[], stem: string, answer: 0 | 1, explanation: string, difficulty: 1 | 2 | 3 | 4 | 5 = 1): ExamQuestion => {
  return withReview({ id, subject, chapter, knowledge_tags: tags, type: 'judge', stem, options: ['正确', '错误'], answer, explanation, difficulty });
}

export const examBank20: ExamQuestion[] = [
  s('bf001', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf002', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance', 'k_mental_account'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf003', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf004', 'exam_bank_pf', '从众', ['herd', 'behavior_finance', 'k_recency_bias'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf005', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf006', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf007', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf008', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf009', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf010', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
  s('bf011', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf012', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf013', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf014', 'exam_bank_pf', '从众', ['herd', 'behavior_finance'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf015', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf016', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf017', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf018', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf019', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf020', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
  s('bf021', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf022', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf023', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf024', 'exam_bank_pf', '从众', ['herd', 'behavior_finance'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf025', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf026', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf027', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf028', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf029', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf030', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
  s('bf031', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf032', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf033', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf034', 'exam_bank_pf', '从众', ['herd', 'behavior_finance'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf035', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf036', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf037', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf038', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf039', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf040', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
  s('bf041', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf042', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf043', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf044', 'exam_bank_pf', '从众', ['herd', 'behavior_finance'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf045', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf046', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf047', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf048', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf049', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf050', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
  s('bf051', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf052', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf053', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf054', 'exam_bank_pf', '从众', ['herd', 'behavior_finance'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf055', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf056', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf057', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf058', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf059', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf060', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
  s('bf061', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf062', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf063', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf064', 'exam_bank_pf', '从众', ['herd', 'behavior_finance'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf065', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf066', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf067', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf068', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf069', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf070', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
  s('bf071', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf072', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf073', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf074', 'exam_bank_pf', '从众', ['herd', 'behavior_finance'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf075', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf076', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf077', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf078', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf079', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf080', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
  s('bf081', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf082', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf083', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf084', 'exam_bank_pf', '从众', ['herd', 'behavior_finance'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf085', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf086', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf087', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf088', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf089', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf090', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
  s('bf091', 'exam_bank_pf', '损失厌恶', ['behavior_finance', 'loss_aversion'], '客户亏损 10% 的痛苦约是盈利 10% 快乐的两倍，这叫（）。', ['损失厌恶', '锚定', '从众', '过度自信'], 0, '卡尼曼与特沃斯基的前景理论。', 2),
  s('bf092', 'exam_bank_pf', '处置效应', ['disposition_effect', 'behavior_finance'], '投资者急于卖出盈利基金却死扛亏损基金，称为（）。', ['处置效应', '定投', '再平衡', '分散'], 0, '卖盈扛亏是统计上最普遍的行为偏差。', 3),
  m('bf093', 'exam_bank_pf', '锚定', ['anchoring', 'behavior_finance'], '关于「锚定」，下列说法正确的有（）。', ['成本价锚定', '趋势跟随', '资产配置', '风险预算'], [0], '用"空仓重购测试"矫正。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf094', 'exam_bank_pf', '从众', ['herd', 'behavior_finance'], '判断：关于从众——羊群效应。', 0, '发行量是反向指标的原因。', 2),
  s('bf095', 'exam_bank_pf', '过度自信', ['overconfidence', 'behavior_finance'], '牛市里频繁交易的散户往往收益落后，主要因为（）。', ['过度自信导致的频繁交易与择时错误', '本金太少', '运气差', '费率太高'], 0, '过度自信+交易磨损是收益杀手。', 1),
  s('bf096', 'exam_bank_pf', '心理账户', ['mental_accounting', 'behavior_finance'], '客户把工资、奖金、彩票收入放进不同"心理账户"区别对待，属于（）。', ['心理账户效应', '理性配置', '预算管理', '目标导向'], 0, '钱是同质的，框架让决策失真。', 2),
  s('bf097', 'exam_bank_pf', '近因效应', ['recency_bias', 'behavior_finance'], '客户因近期大涨就认为会一直涨，属于（）。', ['近因偏差', '长期主义', '均值回归', '逆向思维'], 0, '追涨的心理学根源。', 3),
  m('bf098', 'exam_bank_pf', '框架效应', ['framing', 'behavior_finance'], '关于「框架效应」，下列说法正确的有（）。', ['框架效应', '锚定效应', '确认偏差', '损失厌恶'], [0], '同一事实不同表述改变决策。（唯一正确项为 0，其余为典型错误说法。）', 4),
  j('bf099', 'exam_bank_pf', '确认偏差', ['confirmation_bias', 'behavior_finance'], '判断：关于确认偏差——确认偏差。', 0, '理财经理要提供反方证据。', 2),
  s('bf100', 'exam_bank_pf', '后悔厌恶', ['regret_aversion', 'behavior_finance'], '客户不敢买入"错过已久"的资产，属于（）。', ['后悔厌恶与错失恐惧', '价值投资', '均值回归', '再平衡'], 0, 'FOMO 与后悔厌恶一体两面。', 1),
];
